spring.application.name=loanmanagement

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/loan
spring.datasource.username=postgres
spring.datasource.password=poorvaja

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Hikari Connection Pool
spring.datasource.hikari.auto-commit=false
# Disable auto-commit for LOB support

# File upload limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
